### ISSUE TITLE
venvctrl 0.4.0 sometimes fails in venvctrl-relocate

### ISSUE THREAD

**Issue by kdoren** [kevinconway/venvctrl#12]
Hi Kevin, thanks very much for making rpmvenv available, it's a really good tool.

We had our builds break recently after you released venvctrl 0.4.0 (error messages below).  This failed on our Jenkins server but work on another server I build on, so I can't explain how to reproduce it.   Forcing install of venvctrl==0.3.0 appears to correct the issue.

The failure is in venvctrl-relocate.  Error looks like this:

+ venvctrl-relocate --source=/tmp/rpmvenvCUXWSz/BUILDROOT/spoken-sbc-api-mpact-3.0.0-rc.41472.x86_64//usr/local/spoken/sbc-api-mpact/env --destination=//usr/local/spoken/sbc-api-mpact/env
Traceback (most recent call last):
  File "/usr/bin/venvctrl-relocate", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/venvctrl/cli/relocate.py", line 52, in main
    relocate(args.source, args.destination, args.move)
  File "/usr/lib/python2.7/site-packages/venvctrl/cli/relocate.py", line 24, in relocate
    venv.relocate(destination)
  File "/usr/lib/python2.7/site-packages/venvctrl/venv/relocate.py", line 75, in relocate
    next_dir = dirs.pop()
IndexError: pop from empty list
error: Bad exit status from /var/tmp/rpm-tmp.P0sH7s (%install)

Thanks,
Kevin

**Comment by kevinconway** [comment]
@kdoren Yeah, I see the bug now. Both the .pth processing loop _and_ the test were faulty in similar ways that resulted in two issues. The big one is the pop from empty list you've seen. That happens when the last directory in the virtualenv is processed and is caused by a faulty loop condition. The second issue that this helped uncover is that the full virtualenv wasn't actually being processed for .pth files. Only the first layer of directories was being inspected. 

I've updated the test and patched the .pth processing loop in https://github.com/kevinconway/venvctrl/pull/13 . Once everything goes green I'll merge and release as `0.4.1`.

**Comment by kevinconway** [comment]
`0.4.1` is released and should resolve this issue. If it doesn't then please re-open this so we can figure out what else is wrong.

Thanks for putting in the bug report!

**Comment by kdoren** [comment]
That was quick!  Thanks very much, that seems to have fixed it.
