### ISSUE TITLE
Dependency on virtualenv not declared

### ISSUE THREAD

**Issue by jayvdb** [kevinconway/venvctrl#17]
setup.* should declare a dependency on virtualenv

**Comment by jayvdb** [comment]
Also `pip` is needed.  Declaring this also will help with distro packaging tools, where pip is not necessarily always present.

**Comment by kevinconway** [comment]
I've added `virtualenv` to the `install_requires` section of the `setup.py` and also added a version range for it to the `requirements.txt` for local installs and tests.

I didn't add `pip` because it's not required on the host or any virtualenv in which `venvctrl` is installed. It is only required to be present within the virtualenv being managed and it seems to be installed by default in all virtualenvs. If it's not actually installed by default but simply aliased from the host installation into the virtualenv, or something similar, then feel free to re-open the issue and I can see about adding `pip`.
