### ISSUE TITLE
Breaking changes from virtualenv

### ISSUE THREAD

**Issue by somedmguy** [kevinconway/venvctrl#32]
There are several unit test failures with versions 20.26.6 & 20.27.0 of virtualenv.
Presumably the change to VIRTUAL_ENV in the activate script is the culprit: https://github.com/pypa/virtualenv/pull/2771/commits/63cb3a8574632b4e2b9de7db560d50e1bacaac59

**Comment by kevinconway** [comment]
You're right. The patch you linked to broke the relocation feature by changing how virtualenv renders paths in the activation scripts. I had some time this morning to make a patch here: https://github.com/kevinconway/venvctrl/pull/33. The fix is pretty small and backwards compatible with older versions of virtualenv.

Thanks for linking to the actual change from virtualenv! That made things much easier for me.

**Comment by kevinconway** [comment]
This should be fixed in version 0.8.0.
