### ISSUE TITLE
Python 3.12 venv activate script has 2 occurences of VIRTUAL_ENV export, venvctrl-relocate stops to first one

### ISSUE THREAD

**Issue by ArthurGarnier** [kevinconway/venvctrl#35]
Hi,

When creating a new venv with python 3.12 (RHEL8 or RHEL9, python 3.12.1, venvctrl 0.8.0), the activate script contains 2 occurence of "VIRTUAL_ENV" export : 

```
[root@f0c8018ae854 ~]# python3.12 -m venv test
[root@f0c8018ae854 ~]# grep "export VIRTUAL_ENV=" test/bin/activate
    export VIRTUAL_ENV=$(cygpath "/root/test")
    export VIRTUAL_ENV="/root/test"
```
 
Running a relocate seems to only replace the first occurence : 

```
[root@f0c8018ae854 ~]# venvctrl-relocate --source /root/test/ --destination /root/test2
[root@f0c8018ae854 ~]# grep "export VIRTUAL_ENV=" test/bin/activate
    export VIRTUAL_ENV=/root/test2
    export VIRTUAL_ENV="/root/test"
```

The line https://github.com/kevinconway/venvctrl/blob/f3a5035e7516fa49bff0a7585dc5dd82b3712f74/venvctrl/venv/base.py#L306 seems responsible of the bug, by ending the function processing and stopping to the first matching line.

Regards,

**Comment by kevinconway** [comment]
The root cause ended up being a bug in the regular expression pattern used to find the first occurrence of `VIRTUAL_ENV=` and capture the assigned value. The code was already supposed to rewrite multiple occurrences but the extracted path value only ever matched a single occurrence. One issue is that the regular expression matched on `^ *export VIRTUAL_ENV=["']?(.*)["']?$` which matched the first line in your example and captured the value `$(cygpath "/root/test")`. It then rewrote all occurrences of that value to the new path but there is only one occurrence. The pattern was meant to match the second example and result in `/root/test` as the captured value. There were two other, smaller bugs in the pattern as well. I made a patch to fix this here: https://github.com/kevinconway/venvctrl/pull/36

**Comment by kevinconway** [comment]
You should be able to pull in 0.9.0 and resolve the issue
