### ISSUE TITLE
venvctrl relocate doesn't handle exec

### ISSUE THREAD

**Issue by MeabhG** [kevinconway/venvctrl#4]
When building a rpm with `rpmvenv` that has a very long long path name, files in /usr/bin/ have an `exec`  added to the top of the python files rather then a python shebang, see example of the top  /usr/bin/circusd:

```
#!/bin/sh
'''exec' /tmp/rpmvenvN0vF_Y/BUILDROOT/python-circus-0.14.0-10.el6.company_name.x86_64/usr/share/python-circus/python_circus_venv/bin/python "$0" "$@"
' '''
```

vencctrl doesn't relocate the files when they have an `exec` and the `rpmvenv` build will complete 'successfully'. Preferred behaviour would be to handle `exec` or raise an exception with a detailed error message when `exec` is found.

**Comment by kevinconway** [comment]
I was wondering how pip/virtualenv would eventually address this issue. When I started this project, and rpmvenv, it was simply a known limitation for Python packages and not much we could do. It looks like this is a fairly recent change in pip and the dh_virtualenv folks are working to address the same thing: https://github.com/spotify/dh-virtualenv/issues/225.

In this case, we might need to add some more intelligence to the BinFile (https://github.com/kevinconway/venvctrl/blob/master/venvctrl/venv/base.py#L146) so that it can detect these.... "alternative" shebangs and manage them correctly.

Is this a PR you might be able to make?
